[global]
	checkNewVersion = true

[log]
	filePath = '/opt/traefik/logs/error.log'
	level ='INFO'

[accessLog]
	filePath = '/opt/traefik/logs/access.log'


[api]
	dashboard = true

[providers.docker]
	endpoint = 'unix:///var/run/docker.sock'
	exposedByDefault = false

 [entryPoints]
   [entryPoints.web]
     address = ":80"
   [entryPoints.websecure]
     address = ":443"

[http.middlewares.auth.basicauth]
	users = ['wearenv:$apr1$ZV0Qj.FR$/hfr9d7.5o8XLMRMJpf7x.']
	realm = 'Restricted'

[http.middlewares.redirect-to-https.redirectScheme]
	scheme = 'https'
